package JKMTells;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class JKMArrayStructure {
    static private ArrayList<String> list_1  = new ArrayList<>(Arrays.asList("Proszę zwrócić uwagę:","I tak mam trzy razy mniej czasu, proszę mi pozwolić powiedzieć:","Państwo się śmieją, ale","Ja nie potrzebowałem edukacji seksualnej, żeby wiedzieć, że","No niestety:","Gdzie leży przyczyna problemu? Ja państwu powiem","Państwo chyba nie widzą, że","Oświadczam kategorycznie:","Powtarzam:","Powiedzmy to z całą mocą:","W Polsce dzisiaj","Państwo sobie nie zdają sprawy, że","To ja przepraszam bardzo:","Otóż nie wiem, czy pan wie, że","Yyyyy...","Ja chcę powiedzieć jedną rzecz:","Trzeba powiedzieć jasno:","Jak powiedział krakowianin Stanisław Lem,","Proszę mnie dobrze zrozumieć:","Ja chciałem państwu przypomnieć, że","Niech państwo nie mają złudzeń:","Powiedzmy to wyraźnie:"));
    static private ArrayList<String> list_2  = new ArrayList<>(Arrays.asList("właściciele niewolników","banda kurew i złodziei","pisiory","związkowcy","trokiści","tak zwane dzieci kwiaty","rozmaici urzędnicy","federści","etatyści","ci durnie i złodzieje","ludzie wybrani głosami meneli spod budki z piwem","socjaliści pobożni","socjaliści bezbożni","komuniści z krzyżem w zębach","agenci obcych służb","członkowie Bandy Czworga","pseudo-masoni z Wielkiego Wschodu Francji","przedstawiciele czerwonej hołoty","ci wszyscy (tfu!) geje","funkcjonariusze reżymowej telewizji","tak zwani ekolodzy","ci wszyscy (tfu!) demokraci","agenci bezpieki","feminazistki"));
    static private ArrayList<String> list_3  = new ArrayList<>(Arrays.asList("Po przeczytaniu Manifestu komunistycznego","którymi się brzydzę","których nienawidzę","z okolic Gazety Wyborczej","czyli taka żydokomuna","odkąd zniesiono karę śmierci","którymi pogardzam","których miejsce w normalnym kraju jest w więzieniu","na polecenie Brukseli","posłusznie","bezmyślnie","z nieprawdopodobną pogardą dla człowieka","za pieniądze podatników","zgodnie z ideologią LGBTQZ","za wszelką cenę","zupełnie bezkarnie","całkowicie bezczelnie","o poglądach na lewo od komunizmu","celowo i świadomie","z premedytacją","od czasów Okrągłego Stołu","w ramach postępu"));
    static private ArrayList<String> list_4  = new ArrayList<>(Arrays.asList("udają homoseksualistów","niszczą rodzinę","robią laskę","idą do polityki","zakazują góralom robienia oscypków","organizują paraolimpiady","wprowadzają ustrój, w którym raz na cztery lata można wybrać sobie pana","ustawiają fotoradary","wprowadzają dotacje","wydzielają buspasy","podnoszą wiek emerytalny","rżną głupa","odbierają dzieci rodzicom","wprowadzają absurdalne przepisy","umiesczają dzieci w szkołach koedukacyjnych","wprowadzają parytety","nawołują do podniesienia podatków","próbują wyrzucić kierowców z miast","próbują skłócić Polskę z Rosją","głoszą brednie o globalnym ociepleniu","zakazują posiadania broni","nie dopuszczają prawicy do władzy","uczą dzieci homoseksualizmu"));
    static private ArrayList<String> list_5  = new ArrayList<>(Arrays.asList("żeby poddawać wszystkich tresurze","bo taka jest ich natura","bo chcą wszystkich kontrolować","bo nie rozumieją, że socjalizm nie działa","żeby wreszczie zapanował socjalizm","dokładnie tak jak towarzysz Janosik","zamiast pozwolić ludziom zarabiać","żeby wyrwać kobiety z domu"," bo to jest w interesie tak zwanych ludzi pracy","zamiast pozwolić decydować konsumentowi","żeby nie opłacało się mieć dzieci","zamiast obniżyć podatki","bo nie rozumieją, że selekcja naturalna jest czymś dobrym","żeby meżczyzni przestali być agresywni","bo dzięki temu mogą brać łapówki","bo dzięki temu mogą kraść","bo dostają za to pieniądze","bo tak się uczy w państwowej szkole","bo bez tego (tfu!) demokracja nie może istnieć","bo głupich jest więcej niż mądrych","bo chcą tworzyć raj na ziemi","bo chcą niszczyć cywilizację białego człowieka"));
    static private ArrayList<String> list_6  = new ArrayList<>(Arrays.asList("co ma z resztą tyle samo sensu, co zawody w szachach dla debili.","co zostało dokładnie zaplanowane w Magdalence przez śp. generała Kiszczaka.","i trzeba być idiotą, żeby ten system popierać.","ale nawet ja jesczę dożyję normalnych czasów.","co dowodzi, że wyskrobano nie tych, co trzeba.","a zwykłym ludziom wmawiają, że im coś 'dadzą'.","-coż: chcieliście (tfu!) demokracji, to macie.","dlatego trzeba zlikwidować koryto, a nie zmieniać świnie.","a wystarczyłoby przestać wypłacać zasiłki","podczas gdy normalni ludzie uważani są za dziwaków.","co w wieku XIX po prostu by wyśmiano.","-dlatego w społecześntwie jest równość, a powinno być rozwarstwienie.","co prowadzi Polskę do katastrofy.","-dlatego trzeba przywrócic normalność.","ale w wolnej Polsce pójdą siedzieć.","przez kolejne kadencje.","o czym się nie mówi.","i właśnie dlatego Europa umiera.","ale przyjdą muzułmanie i zrobią porządek.","-tak samo zresztą jak za Hitlera.","-proszę zobaczyć, co się dzieje na Zachodznie, jeśli mi państwo nie wierzą.","co lat temu sto nikomu nie przyszłoby nawet do głowy."));

    static private ArrayList<ArrayList<String>> all_Lists = new ArrayList<ArrayList<String>>(List.of(list_1,list_2,list_3,list_4,list_5,list_6));

    public static ArrayList<ArrayList<String>> getAll_Lists() {
        return all_Lists;
    }
}
